version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "donkomura"
    assignees:
      - "donkomura"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10