[package]
name = "rjq"
version = "0.1.0"
edition = "2024"

[dependencies]
atty = "0.2"
crossterm = "0.29.0"
jaq-core = "2.2.1"
jaq-json = { version = "1.1.3", features = ["serde_json"] }
jaq-std = "2.1.2"
ratatui = "0.29.0"
serde_json = "1.0.142"
thiserror = "1.0"
